name: risa_reborn
description: Made by Trio Turu.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  badges: ^2.0.2
  cached_network_image: ^3.2.0
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  date_time_picker: ^2.1.0
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_secure_storage: ^5.1.0
  flutter_snake_navigationbar: ^0.6.1
  flutter_speed_dial: ^6.0.0
  get: ^4.6.1
  get_storage: ^2.0.3
  hive: ^2.2.0
  hive_flutter: ^1.1.0
  http: ^0.13.4
  intl: ^0.17.0
  modal_bottom_sheet: ^2.1.0
  shared_preferences_web: ^2.0.4
  shimmer: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logo_bumn.png
    - assets/images/logo_pds.png
    - assets/images/logo_pelindo.png
    - assets/images/icon_risa.png
    - assets/images/no_image.png
